Application\ShopBundle\Entity\Product:
    type: entity
    table: user
    id:
        id:
            type: integer
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            length: 5
