#src/Application/ShopBundle/Resources/config/routing.yml
shop_product:
  pattern: /product
  defaults: { _controller: ShopBundle:Product:list }

shop_product_edit_list:
  pattern: /product/editlist
  defaults: { _controller: ShopBundle:Product:editList }

shop_product_new:
  pattern: /product/new
  defaults: { _controller: ShopBundle:Product:new }

shop_product_create:
  pattern: /product/create
  defaults: { _controller: ShopBundle:Product:create }

shop_category_new:
  pattern: /category/new
  defaults: { _controller: ShopBundle:Category:new }

shop_admin:
  pattern: /admin
  defaults: {_controller: ShopBundle:Shop:index}